server:
  port: 8090

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ivanyavila/java-academia-configs
          clone-on-start: true
#  profiles:
#    active: native
#          https://github.com/rivalix/service-configuration
